server:
  port: 8084
  ssl:
    enabled: false

bot:
  name: ${TG_BOT_NAME}
  token: ${TG_BOT_TOKEN}
  owner: ${TG_BOT_OWNER}
  uri: ${TG_BOT_URI}
  muteanswer: false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RMQ_USER}
    password: ${RMQ_PASSWORD}
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message