server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tgbotmiddle
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    generate-ddl: true

salt:
  photo: ${TG_BOT_SALT_PHOTO}
  doc: ${TG_BOT_SALT_DOC}
  userid: ${TG_BOT_SALT_USERID}